services:
  - type: worker
    name: telegram_guardian_worker
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python monitor.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_TOKEN
      - key: TELEGRAM_CHAT_ID
        value: YOUR_TELEGRAM_CHAT_ID
